/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.esi.g34840.carrefour.gui;


import be.esi.g34840.carrefour.concept.CarrefourVueInterface;
import be.esi.g34840.carrefour.dto.CarrefourEtat;
import be.esi.g34840.carrefour.model.Carrefour;
import javax.swing.JFrame;

/**
 * Classe qui crée un dialog qui permet de prévisualiser les paramètres sur un carrefour
 * @author J4un3
 */
public class PrevisualisationGUI extends javax.swing.JDialog implements CarrefourVueInterface {

    public static int FEUX_PIETON_E_O = 3, FEUX_PIETON_N_S = 2,
            FEUX_VEHICULE_E_O = 1, FEUX_VEHICULE_N_S = 0;
    /**
     * Creates new form PrevisualisationGUI
     */
    private int[] vert, orange, rouge;
    private int rougeCommun;
    private Carrefour carrefour;
    private String[] nomAxe;
    public PrevisualisationGUI(CarrefourClientAdministrateurGUI gui) {
        super(new JFrame(), true);
        initComponents();
        vert = new int[]{(Integer) gui.getJTable1().getValueAt(0, 1), (Integer) gui.getJTable1().getValueAt(1, 1), (Integer) gui.getJTable1().getValueAt(2, 1), (Integer) gui.getJTable1().getValueAt(3, 1)};
        orange = new int[]{(Integer) gui.getJTable1().getValueAt(0, 2), (Integer) gui.getJTable1().getValueAt(1, 2), (Integer) gui.getJTable1().getValueAt(2, 2), (Integer) gui.getJTable1().getValueAt(3, 2)};
        rouge = new int[]{(Integer) gui.getJTable1().getValueAt(0, 3), (Integer) gui.getJTable1().getValueAt(1, 3), (Integer) gui.getJTable1().getValueAt(2, 3), (Integer) gui.getJTable1().getValueAt(3, 3)};
        rougeCommun = gui.getJSlider1().getValue();
        feuPIeton1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Piéton Nord-Sud"));
        feuPIeton1.setFeuNS(true);
        feuPieton2.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Piéton Est-Ouest"));
        feuPieton2.setFeuNS(false);
        feuVehicule1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Véhicule Nord-Sud"));
        feuVehicule1.setFeuNS(true);
        feuVehicule2.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Véhicule Est-Ouest"));
        feuVehicule2.setFeuNS(false);
        this.nomAxe = gui.getNomAxe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previP = new javax.swing.JPanel();
        feuVehicule1 = new be.esi.g34840.carrefour.gui.FeuVehicule();
        feuVehicule2 = new be.esi.g34840.carrefour.gui.FeuVehicule();
        feuPIeton1 = new be.esi.g34840.carrefour.gui.FeuPieton();
        feuPieton2 = new be.esi.g34840.carrefour.gui.FeuPieton();
        configPanel = new javax.swing.JPanel();
        sliderVitesse = new javax.swing.JSlider();
        vitesseL = new javax.swing.JLabel();
        visuB = new javax.swing.JToggleButton();
        msL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prévisualisation Carrefour");

        previP.setBorder(javax.swing.BorderFactory.createTitledBorder("Prévisualisation du carrefour"));

        org.jdesktop.layout.GroupLayout previPLayout = new org.jdesktop.layout.GroupLayout(previP);
        previP.setLayout(previPLayout);
        previPLayout.setHorizontalGroup(
            previPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(previPLayout.createSequentialGroup()
                .addContainerGap()
                .add(feuVehicule1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(feuPIeton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(feuVehicule2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(feuPieton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        previPLayout.linkSize(new java.awt.Component[] {feuPIeton1, feuPieton2, feuVehicule1, feuVehicule2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        previPLayout.setVerticalGroup(
            previPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(previPLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(previPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, feuVehicule1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, feuPIeton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, feuVehicule2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, feuPieton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        configPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuration de la prévisualisation"));

        sliderVitesse.setMajorTickSpacing(100);
        sliderVitesse.setMaximum(1000);
        sliderVitesse.setMinimum(100);
        sliderVitesse.setMinorTickSpacing(100);
        sliderVitesse.setPaintLabels(true);
        sliderVitesse.setPaintTicks(true);
        sliderVitesse.setSnapToTicks(true);
        sliderVitesse.setToolTipText("vitesse d'un tick qui vaut en réalité 1 seconde");
        sliderVitesse.setValue(1000);
        sliderVitesse.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVitesseStateChanged(evt);
            }
        });

        vitesseL.setText("Vitesse de la prévisualisation :");

        visuB.setText("Visualiser");
        visuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visuBActionPerformed(evt);
            }
        });

        msL.setText("1000 ms : 1000 ms");

        org.jdesktop.layout.GroupLayout configPanelLayout = new org.jdesktop.layout.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(vitesseL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sliderVitesse, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, configPanelLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(msL)
                .add(20, 20, 20))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, configPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(visuB)
                .add(305, 305, 305))
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(configPanelLayout.createSequentialGroup()
                .add(configPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(sliderVitesse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(configPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(vitesseL)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(msL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 22, Short.MAX_VALUE)
                .add(visuB)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(previP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(configPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(previP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(configPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visuBActionPerformed
        if (visuB.isSelected()) {
            sliderVitesse.setEnabled(false);
            visuB.setText("Stop");
            carrefour = new Carrefour(vert, orange, rouge, rougeCommun, sliderVitesse.getValue(),nomAxe);
            carrefour.abonne(this);
        } else {
            carrefour.desabonne(this);
            carrefour.stop();
            carrefour = null;
            sliderVitesse.setEnabled(true);
            visuB.setText("Prévisualiser");
        }
    }//GEN-LAST:event_visuBActionPerformed

    private void sliderVitesseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVitesseStateChanged
        msL.setText(sliderVitesse.getValue() + " ms : 1000 ms");
    }//GEN-LAST:event_sliderVitesseStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrevisualisationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrevisualisationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrevisualisationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrevisualisationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrevisualisationGUI dialog = new PrevisualisationGUI(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel configPanel;
    private be.esi.g34840.carrefour.gui.FeuPieton feuPIeton1;
    private be.esi.g34840.carrefour.gui.FeuPieton feuPieton2;
    private be.esi.g34840.carrefour.gui.FeuVehicule feuVehicule1;
    private be.esi.g34840.carrefour.gui.FeuVehicule feuVehicule2;
    private javax.swing.JLabel msL;
    private javax.swing.JPanel previP;
    private javax.swing.JSlider sliderVitesse;
    private javax.swing.JToggleButton visuB;
    private javax.swing.JLabel vitesseL;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        CarrefourEtat etat = carrefour.getEtat();
        feuVehicule1.update(etat);
        feuVehicule2.update(etat);
        feuPIeton1.update(etat);
        feuPieton2.update(etat);
    }
}
