/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.esi.g34840.carrefour.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.io.Serializable;
import javax.swing.JDialog;

/**
 *
 * @author J4un3
 */
public class Led extends javax.swing.JPanel implements Serializable {

    private Color color;
    private boolean on;
    public static final String ON_CHANGE = "on";

    /**
     * Creates new form Led
     */
    public Led() {
        initComponents();
    }

    /**
     * Get the value of color
     *
     * @return the value of color
     */
    public Color getColor() {
        return color;
    }

    /**
     * Set the value of color
     *
     * @param color new value of color
     */
    public void setColor(Color color) {
        this.color = color;
        repaint();
    }

    /**
     * Get the value of on
     *
     * @return the value of on
     */
    public boolean isOn() {
        return on;
    }

    /**
     * Set the value of on
     *
     * @param on new value of on
     */
    public void setOn(boolean on) {
        this.on = on;
        repaint();
        firePropertyChange(ON_CHANGE, !this.on, this.on);    // averti les composants inscrits, notifie le chgmt.
    }

    /**
     * Inverse the color of the led
     */
    public void inverse() {
        this.on = !on;
        repaint();
        firePropertyChange(ON_CHANGE, !on, on);    // averti les composants inscrits, notifie le chgmt.
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);    // pour ne peindre que la partie qui concerne le cercle ( sinon il refait avec le boutons en arriere plan.
        g.setColor(color);
        int c = Math.min(getWidth(), getHeight());
        g.drawOval(0, 0, c, c);
        if (on) {
            g.fillOval(0, 0, c, c);
        }
    }

    public static void main(String[] args) {
        JDialog dialog = new JDialog();
        dialog.add(new Led());
        dialog.setVisible(true);
        dialog.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
