/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.esi.g34840.carrefour.gui;

import be.esi.g34840.carrefour.business.CarrefourServeurInterface;
import be.esi.g34840.carrefour.implementation.VueCarrefourClientPieton;
import be.esi.gui.outils.MsgOutils;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.rmi.ConnectException;
import java.rmi.RemoteException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;

/**
 * Classe qui permet au client piéton d'observer selon sa vue et d'interagir avec le modèle
 * via le bouton poussoire 
 *
 * @author g34840
 */
public class CarrefourClientPietonGUI extends javax.swing.JDialog {

    public static int FEUX_PIETON_E_O = 3, FEUX_PIETON_N_S = 2;
    private CarrefourServeurInterface serveur;
    private VueCarrefourClientPieton client;
    private Timer timer;
    private TimerTask timerTask;

    /**
     * Creates new form CarrefourClientPietonGUI
     */
    public CarrefourClientPietonGUI(final CarrefourServeurInterface serveur) {
        super(new JFrame(), false);
        timer = new Timer();
        //Permet de rester en contact avec le serveur, si celui-ci n'est plus on-line on bascule en mode warning
        timerTask = new TimerTask() {
            @Override
            public void run() {
                try {
                    serveur.isAlive();
                } catch (RemoteException ex) {
                    warning();
                }
            }
        };
        // verifie la connection avec le serveur tout les 5 secondes
        timer.schedule(timerTask, 0, 5000);
        initComponents();
        feuPieton1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Piéton Nord-Sud"));
        try {
            this.serveur = serveur;
            this.client = new VueCarrefourClientPieton(this);
            serveur.abonne(client);
            // Permet de se désabonner une fois la fenêtre fermée.
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    try {
                        serveur.desabonne(client);
                        System.exit(0);
                    } catch (RemoteException ex) {
                        MsgOutils.erreur("RemoteException", ex.getMessage());
                        System.exit(0);
                    }
                }
            });
        } catch (ConnectException ex) {
            MsgOutils.erreur("ConnecException", "Problème de connection. L'application va se fermer.");
            System.exit(0);
        } catch (RemoteException ex) {
            MsgOutils.erreur("Client RemoteException", ex.getMessage());
            System.exit(0);
        }
    }

    /**
     * Permet de passer en mode warning
     */
    private void warning() {
        timerTask.cancel();
        poussoirB.setEnabled(false);
        feuPieton1.setFeuWarning();
    }

    /**
     * Methode qui reçoit les changements du serveur
     *
     * @throws RemoteException si il y a un problème de connection avec le
     * serveur
     */
    public void update() throws RemoteException {
        feuPieton1.update(serveur.getEtat());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        optionP = new javax.swing.JPanel();
        radioANSB = new javax.swing.JRadioButton();
        radioAEOB = new javax.swing.JRadioButton();
        boutonP = new javax.swing.JPanel();
        poussoirB = new javax.swing.JButton();
        feuPieton1 = new be.esi.g34840.carrefour.gui.FeuPieton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        optionP.setBorder(javax.swing.BorderFactory.createTitledBorder("Option Axe"));

        buttonGroup1.add(radioANSB);
        radioANSB.setSelected(true);
        radioANSB.setText("Axe Nord-Sud");
        radioANSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioANSBActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioAEOB);
        radioAEOB.setText("Axe Est-Ouest");
        radioAEOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAEOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPLayout = new javax.swing.GroupLayout(optionP);
        optionP.setLayout(optionPLayout);
        optionPLayout.setHorizontalGroup(
            optionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(optionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioANSB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioAEOB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        optionPLayout.setVerticalGroup(
            optionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioANSB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioAEOB))
        );

        boutonP.setBorder(javax.swing.BorderFactory.createTitledBorder("Bouton Poussoir"));

        poussoirB.setText("Push");
        poussoirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poussoirBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boutonPLayout = new javax.swing.GroupLayout(boutonP);
        boutonP.setLayout(boutonPLayout);
        boutonPLayout.setHorizontalGroup(
            boutonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boutonPLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(poussoirB)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        boutonPLayout.setVerticalGroup(
            boutonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boutonPLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(poussoirB)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boutonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(feuPieton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boutonP, optionP});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(feuPieton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Permet de basculer sur l'axe Nord-Sud
     *
     * @param evt
     */
    private void radioANSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioANSBActionPerformed
        feuPieton1.setFeuNS(true);
        feuPieton1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Piéton Nord-Sud"));
    }//GEN-LAST:event_radioANSBActionPerformed
    /**
     * Permet de basculer sur l'axe Est-Ouest
     *
     * @param evt
     */
    private void radioAEOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAEOBActionPerformed
        feuPieton1.setFeuNS(false);
        feuPieton1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Piéton Est-Ouest"));

    }//GEN-LAST:event_radioAEOBActionPerformed
    /**
     * Permet d'actionner le bouton poussoir
     *
     * @param evt
     */
    private void poussoirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poussoirBActionPerformed
        try {
            serveur.poussoir(feuPieton1.getFeuNS() ? FEUX_PIETON_N_S : FEUX_PIETON_E_O);
        } catch (RemoteException ex) {
            MsgOutils.erreur("RemoteException", ex.getMessage());
        }
    }//GEN-LAST:event_poussoirBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrefourClientPietonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrefourClientPietonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrefourClientPietonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrefourClientPietonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarrefourClientPietonGUI dialog = new CarrefourClientPietonGUI(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boutonP;
    private javax.swing.ButtonGroup buttonGroup1;
    private be.esi.g34840.carrefour.gui.FeuPieton feuPieton1;
    private javax.swing.JPanel optionP;
    private javax.swing.JButton poussoirB;
    private javax.swing.JRadioButton radioAEOB;
    private javax.swing.JRadioButton radioANSB;
    // End of variables declaration//GEN-END:variables
}
