/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.esi.g34840.carrefour.gui;

import be.esi.g34840.carrefour.dto.CarrefourEtat;
import java.awt.Color;

/**
 * Classe qui affiche un feu piéton
 *
 * @author g34840
 */
public class FeuPieton extends javax.swing.JPanel {

    public static int FEUX_PIETON_E_O = 3, FEUX_PIETON_N_S = 2;
    private int clignotant;
    private boolean feuNS;

    /**
     * Creates new form FeuPieton
     */
    public FeuPieton() {
        initComponents();
        ledFeuRouge.setOn(true);
        ledFeuVert.setOn(true);
        feuNS = true;
    }

    public boolean getFeuNS() {
        return feuNS;
    }

    public void setFeuNS(boolean feuNS) {
        this.feuNS = feuNS;
    }

    /**
     * Permet de faire clignoté le feu vert
     */
    private void setFeuVertClignotant() {
        if ((clignotant++) % 2 == 0) {
            ledFeuVert.setColor(Color.green);
        } else {
            ledFeuVert.setColor(Color.black);
        }
    }

    /**
     * Change la couleur des composants graphiques selon l'état des feux
     *
     * @param etat l'état des feux
     */
    public void update(CarrefourEtat etat) {
        switch (etat.getFeux(feuNS ? FEUX_PIETON_N_S : FEUX_PIETON_E_O).getValue()) {
            case 0:
                ledFeuRouge.setColor(Color.black);
                ledFeuVert.setColor(etat.getFeux(feuNS ? FEUX_PIETON_N_S : FEUX_PIETON_E_O).getColor());
                break;
            case 2:
                ledFeuVert.setColor(Color.black);
                ledFeuRouge.setColor(etat.getFeux(feuNS ? FEUX_PIETON_N_S : FEUX_PIETON_E_O).getColor());
                break;
            case 3:
                ledFeuRouge.setColor(Color.black);
                setFeuVertClignotant();
                break;
            case 5:
                ledFeuRouge.setColor(Color.black);
                ledFeuVert.setColor(Color.black);
                break;
        }
    }

    /**
     * Permet de mettre les feux en mode warning
     */
    public void setFeuWarning() {
        ledFeuRouge.setColor(Color.black);
        ledFeuVert.setColor(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ledFeuRouge = new be.esi.g34840.carrefour.gui.Led();
        ledFeuVert = new be.esi.g34840.carrefour.gui.Led();

        setBorder(javax.swing.BorderFactory.createTitledBorder("feu piéton"));

        javax.swing.GroupLayout ledFeuRougeLayout = new javax.swing.GroupLayout(ledFeuRouge);
        ledFeuRouge.setLayout(ledFeuRougeLayout);
        ledFeuRougeLayout.setHorizontalGroup(
            ledFeuRougeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ledFeuRougeLayout.setVerticalGroup(
            ledFeuRougeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ledFeuVertLayout = new javax.swing.GroupLayout(ledFeuVert);
        ledFeuVert.setLayout(ledFeuVertLayout);
        ledFeuVertLayout.setHorizontalGroup(
            ledFeuVertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ledFeuVertLayout.setVerticalGroup(
            ledFeuVertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ledFeuVert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ledFeuRouge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ledFeuRouge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ledFeuVert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private be.esi.g34840.carrefour.gui.Led ledFeuRouge;
    private be.esi.g34840.carrefour.gui.Led ledFeuVert;
    // End of variables declaration//GEN-END:variables
}
