/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.esi.g34840.carrefour.gui;

import be.esi.g34840.carrefour.business.CarrefourServeurInterface;
import be.esi.g34840.carrefour.implementation.VueCarrefourClientVehicule;
import be.esi.gui.outils.MsgOutils;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.rmi.ConnectException;
import java.rmi.RemoteException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;

/**
 * Classe qui permet au client véhicule d'observer le modèle selon sa vue
 *
 * @author g34840
 */
public class CarrefourClientVehiculeGUI extends javax.swing.JDialog {

    public static int FEUX_VEHICULE_N_S = 0;
    public static int FEUX_VEHICULE_E_O = 1;
    private VueCarrefourClientVehicule client;
    private Timer timer;
    private boolean ok;
    private CarrefourServeurInterface serveur;
    private TimerTask timerTask;
    private boolean feuNS;

    /**
     * Creates new form CarrefourClientVehiculeGUI
     */
    public CarrefourClientVehiculeGUI(final CarrefourServeurInterface serveur) {
        super(new JFrame(), true);
        timer = new Timer();
        feuNS = true;
        ok = true;
        //Permet de rester en contact avec le serveur, si celui-ci n'est plus on-line on bascule en mode warning
        timerTask = new TimerTask() {
            @Override
            public void run() {
                try {
                    serveur.isAlive();
                } catch (RemoteException ex) {
                    warning();
                }
            }
        };
        // verifie la connection avec le serveur tout les 5 secondes
        timer.schedule(timerTask, 0, 5000);
        initComponents();
        feuVéhicule1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Véhicule Nord-Sud"));
        try {
            this.client = new VueCarrefourClientVehicule(this);

            this.serveur = serveur;
            serveur.abonne(client);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    try {
                        serveur.desabonne(client);
                        System.exit(0);
                    } catch (RemoteException ex) {
                        MsgOutils.erreur("RemoteException", ex.getMessage());
                        System.exit(0);
                    }
                }
            });
        } catch (ConnectException ex) {
            MsgOutils.erreur("ConnecException", "Problème de connection. L'application va se fermer.");
            System.exit(0);
        } catch (RemoteException ex) {
            MsgOutils.erreur("Client RemoteException", ex.getMessage());
            System.exit(0);
        }
    }
    /**
     * Permet de passer en mode warning
     */
    private void warning() {
        timerTask.cancel();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                feuVéhicule1.setFeuWarning();
            }
        }, 0, 1000);

    }
    /**
     * Methode qui reçoit les changements du serveur
     *
     * @throws RemoteException si il y a un problème de connection avec le
     * serveur
     */
    public void update() throws RemoteException {
        feuVéhicule1.update(serveur.getEtat());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        optionP = new javax.swing.JPanel();
        radioANSB = new javax.swing.JRadioButton();
        radioAEOB = new javax.swing.JRadioButton();
        feuVéhicule1 = new be.esi.g34840.carrefour.gui.FeuVehicule();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        optionP.setBorder(javax.swing.BorderFactory.createTitledBorder("Option Axe"));

        buttonGroup1.add(radioANSB);
        radioANSB.setSelected(true);
        radioANSB.setText("Axe Nord-Sud");
        radioANSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioANSBActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioAEOB);
        radioAEOB.setText("Axe Est-Ouest");
        radioAEOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAEOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPLayout = new javax.swing.GroupLayout(optionP);
        optionP.setLayout(optionPLayout);
        optionPLayout.setHorizontalGroup(
            optionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(optionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAEOB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioANSB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        optionPLayout.setVerticalGroup(
            optionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPLayout.createSequentialGroup()
                .addComponent(radioANSB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioAEOB))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(feuVéhicule1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(feuVéhicule1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Permet de basculer sur l'axe Nord-Sud
     *
     * @param evt
     */
    private void radioANSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioANSBActionPerformed
        feuVéhicule1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Véhicule Nord-Sud"));
        feuVéhicule1.setFeuNS(true);
    }//GEN-LAST:event_radioANSBActionPerformed
    /**
     * Permet de basculer sur l'axe Est-Ouest
     *
     * @param evt
     */
    private void radioAEOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAEOBActionPerformed
        feuVéhicule1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feu Véhicule Est-Ouest"));
        feuVéhicule1.setFeuNS(false);
    }//GEN-LAST:event_radioAEOBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrefourClientVehiculeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrefourClientVehiculeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrefourClientVehiculeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrefourClientVehiculeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarrefourClientVehiculeGUI dialog = new CarrefourClientVehiculeGUI(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private be.esi.g34840.carrefour.gui.FeuVehicule feuVéhicule1;
    private javax.swing.JPanel optionP;
    private javax.swing.JRadioButton radioAEOB;
    private javax.swing.JRadioButton radioANSB;
    // End of variables declaration//GEN-END:variables
}
