/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.esi.g34840.carrefour.gui;

import be.esi.alg3.carrefour.mvc.model.CarrefourEtat;
import be.esi.g34840.carrefour.implementation.VueCarrefourClientVehicule;
import java.awt.Color;

/**
 *
 * @author g34840
 */
public class FeuVehicule extends javax.swing.JPanel {

    public static int FEUX_VEHICULE_N_S = 0;
    public static int FEUX_VEHICULE_E_O = 1;
    private VueCarrefourClientVehicule client;
    private boolean ok;
    private boolean feuNS;

    /**
     * Creates new form FeuVehicule
     */
    public FeuVehicule() {
        initComponents();
        ledFeuOrange.setOn(true);
        ledFeuRouge.setOn(true);
        ledFeuVert.setOn(true);
        feuNS = true;
    }

    public void setFeuNS(boolean feuNS) {
        this.feuNS = feuNS;
    }

    public void setFeuWarning() {
        if (ok) {
            ledFeuOrange.setColor(Color.black);
            ledFeuOrange.setColor(Color.black);
        } else {
            ledFeuOrange.setColor(Color.orange);
            ledFeuOrange.setColor(Color.orange);
        }
        ok = !ok;
        ledFeuRouge.setColor(Color.black);
        ledFeuVert.setColor(Color.black);
    }

    public void update(CarrefourEtat etat) {
        switch (etat.getFeux(feuNS ? FEUX_VEHICULE_N_S : FEUX_VEHICULE_E_O).getValue()) {
            case 0:
                ledFeuRouge.setColor(Color.black);
                ledFeuOrange.setColor(Color.black);
                ledFeuVert.setColor(etat.getFeux(feuNS ? FEUX_VEHICULE_N_S : FEUX_VEHICULE_E_O).getColor());
                break;
            case 1:
                ledFeuRouge.setColor(Color.black);
                ledFeuVert.setColor(Color.black);
                ledFeuOrange.setColor(etat.getFeux(feuNS ? FEUX_VEHICULE_N_S : FEUX_VEHICULE_E_O).getColor());
                break;
            case 2:
                ledFeuVert.setColor(Color.black);
                ledFeuOrange.setColor(Color.black);
                ledFeuRouge.setColor(etat.getFeux(feuNS ? FEUX_VEHICULE_N_S : FEUX_VEHICULE_E_O).getColor());
                break;
            case 5:
                ledFeuRouge.setColor(Color.black);
                ledFeuVert.setColor(Color.black);
                setFeuWarning();
                break;


        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ledFeuRouge = new be.esi.g34840.carrefour.gui.Led();
        ledFeuOrange = new be.esi.g34840.carrefour.gui.Led();
        ledFeuVert = new be.esi.g34840.carrefour.gui.Led();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Feu véhicule"));

        javax.swing.GroupLayout ledFeuRougeLayout = new javax.swing.GroupLayout(ledFeuRouge);
        ledFeuRouge.setLayout(ledFeuRougeLayout);
        ledFeuRougeLayout.setHorizontalGroup(
            ledFeuRougeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ledFeuRougeLayout.setVerticalGroup(
            ledFeuRougeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ledFeuOrangeLayout = new javax.swing.GroupLayout(ledFeuOrange);
        ledFeuOrange.setLayout(ledFeuOrangeLayout);
        ledFeuOrangeLayout.setHorizontalGroup(
            ledFeuOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ledFeuOrangeLayout.setVerticalGroup(
            ledFeuOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ledFeuVertLayout = new javax.swing.GroupLayout(ledFeuVert);
        ledFeuVert.setLayout(ledFeuVertLayout);
        ledFeuVertLayout.setHorizontalGroup(
            ledFeuVertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ledFeuVertLayout.setVerticalGroup(
            ledFeuVertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ledFeuVert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ledFeuOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ledFeuRouge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ledFeuRouge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ledFeuOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ledFeuVert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private be.esi.g34840.carrefour.gui.Led ledFeuOrange;
    private be.esi.g34840.carrefour.gui.Led ledFeuRouge;
    private be.esi.g34840.carrefour.gui.Led ledFeuVert;
    // End of variables declaration//GEN-END:variables
}
